import './globals.css'
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Container, Theme } from '@radix-ui/themes'
import NavBar from './NavBar'
import AuthProvider from './auth/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next APPER',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Theme>
            <NavBar />
            <main className='p-10'>
              <Container mx="auto">
                {children}
              </Container>
            </main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
